apiVersion: apps/v1
kind: Deployment
metadata:
  name: res-deployment
  labels:
    app: res
spec:
  replicas: 10
  selector:
    matchLabels:
      app: res
  template:
    metadata:
      labels:
        app: res
    spec:
      containers:
        - name: res
          image:  payingguest-room-service:0.0.1-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            # You must specify requests for CPU to autoscale
            # based on CPU utilization
            requests:
              cpu: "250m"
            limits:
              cpu: "250m"


