#Server Settings
server:
  port: 8080

spring:
  ## Datasource Properties
  datasource:
    url: jdbc:mysql://192.168.64.3:3306/roomdb
    username: roomuser
    password: roompassword
    ## Hibernate Properties
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  # Application Name
  application:
    name: room-service

#Eureka Service Discovery Settings
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true

# Kafka Config
kafka:
  bootstrap:
    server: 192.168.1.5:9092